swagger: '2.0'
info:
  title: V2C API
  version: 1.0.0
paths:
  /process:
    get:
      summary: Trigger workflow
      operationId: triggerWorkflow
      x-google-backend:
        address: https://REGION-PROJECT_ID.cloudfunctions.net/apiHandler
      responses:
        '200':
          description: Successfully triggered workflow
